def resumo(valor, aumento, redução):
    print('-' * 25)
    print('    RESUMO DO VALOR    ')
    print('-' * 25)
    print(f'Preço analisado: R$ {valor:.2f}')
    print(f'Dobro do preço:  R$ {valor * 2 : .2f}')
    print(f'Metade do preço: R$ {valor / 2 : .2f}')
    print(f'{aumento}% de aumento:  R$ {valor * (1 + aumento / 100) : .2f}')
    print(f'{redução}% de redução:  R$ {valor * (1 - redução / 100) : .2f}')
    print('-' * 25)