def resumo(valor=0, aumento=0, redução=0):
    print('-' * 30)
    print('RESUMO DO VALOR'.center(30))
    print('-' * 30)
    print(f'Preço analisado: R$ {valor:.2f}'.replace('.', ','))
    print(f'Dobro do preço:  R$ {valor * 2 :.2f}'.replace('.', ','))
    print(f'Metade do preço: R$ {valor / 2 :.2f}'.replace('.', ','))
    print(f'{aumento}% de aumento:  R$ {valor * (1 + aumento / 100) :.2f}'.replace('.', ','))
    print(f'{redução}% de redução:  R$ {valor * (1 - redução / 100) :.2f}'.replace('.', ','))
    print('-' * 30)
